name: Update Fancy Job

on:
  workflow_dispatch:
  schedule:
    # Runs the job every day at 00:00 UTC (modify the time as needed)
    - cron: "0 0 * * *"

jobs:
  update-number:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: python -m pip install --upgrade pip

      # Step 4: Run the Python script
      - name: Run Python Script
        run: python update_number.py

      # Step 5: Push Changes
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add number.txt
          git commit -m "Automated update by GitHub Actions"
          git push
