name: Update Fancy Job

on:
  workflow_dispatch:
  schedule:
    # Default cron schedule (runs every day at 00:00 UTC as fallback)
    - cron: "0 0 * * *"

jobs:
  update-number:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Provides write access to the repository contents

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: python -m pip install --upgrade pip

      # Step 4: Run the Python Script
      - name: Run Python Script
        run: python update_number.py

      # Step 5: Configure Git with secrets for user name and email
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      # Step 6: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # The token is automatically provided by GitHub Actions
        run: |
          git add number.txt
          git commit -m "Automated update by GitHub Actions"
          git push
